version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ERGO_PLATFORM_API_URL=https://api.ergoplatform.com/api/v1
    volumes:
      - ./backend/data:/usr/src/app/data
    restart: unless-stopped

volumes:
  backend_node_modules: 